version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 6543:5432
    environment:
      POSTGRES_DB: nest-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    # 데이터 저장 경로를 컨테이너 볼륨에 마운트
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
